import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'generated-index', slug: '/category/getting-started'},
      items: [
        'getting-started/installation',
        'getting-started/hello-world',
        'getting-started/tour',
        'getting-started/project-structure',
        'getting-started/script-mode',
      ],
    },
    {
      type: 'category',
      label: 'Philosophy',
      link: {type: 'generated-index', slug: '/category/philosophy'},
      items: [
        'philosophy/principles',
        'philosophy/semantic-honesty',
        'philosophy/gradual-verification',
        'philosophy/comparisons',
      ],
    },
    {
      type: 'category',
      label: 'Verification',
      link: {type: 'doc', id: 'verification/index'},
      items: [
        'verification/contracts',
        'verification/refinement-reflection',
        'verification/adt-encoding',
        'verification/smt-routing',
        'verification/solver-tuning',
        'verification/proofs',
        'verification/tactic-dsl',
        'verification/trusted-kernel',
        'verification/diakrisis-bridge-roster',
        'verification/counterexamples',
        'verification/proof-export',
        'verification/cubical-hott',
        'verification/framework-axioms',
        'verification/gradual-verification',
        'verification/articulation-hygiene',
        'verification/actic-dual',
        'verification/msfs-coord',
        'verification/owl2',
        'verification/quantitative-types',
        'verification/performance',
        'verification/cli-workflow',
        'verification/proof-corpora',
        'verification/proof-honesty',
        'verification/coord-consistency-audit',
        'verification/coherence',
        'verification/networking',
      ],
    },
    {
      type: 'category',
      label: 'Tooling',
      link: {type: 'generated-index', slug: '/category/tooling'},
      items: [
        'tooling/cli',
        'tooling/build-system',
        'tooling/cog-packages',
        'tooling/testing',
        'tooling/property-testing',
        'tooling/lsp',
        'tooling/vscode-extension',
        'tooling/playbook',
        'tooling/repl',
        'tooling/diagnostics',
        'tooling/tactic-catalogue',
        'tooling/proof-drafting',
        'tooling/proof-repair',
        'tooling/incremental-cache',
        'tooling/auto-paper',
        'tooling/foreign-import',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'doc', id: 'tutorials/overview'},
      items: [
        'tutorials/cli-tool',
        'tutorials/http-service',
        'tutorials/h3-service',
        'tutorials/parser',
        'tutorials/verified-data-structure',
        'tutorials/async-pipeline',
        'tutorials/small-nn',
        'tutorials/refinement-types',
        'tutorials/pattern-matching',
        'tutorials/protocols',
        'tutorials/context-system',
        'tutorials/memory-safety',
        'tutorials/testing-walkthrough',
      ],
    },
    {
      type: 'category',
      label: 'Cookbook',
      link: {type: 'doc', id: 'cookbook/overview'},
      items: [
        'cookbook/file-io',
        'cookbook/json',
        'cookbook/validation',
        'cookbook/regex',
        'cookbook/http-client',
        'cookbook/http-server',
        'cookbook/h3-client',
        'cookbook/h3-server',
        'cookbook/quic-client',
        'cookbook/quic-server',
        'cookbook/tcp',
        'cookbook/dns',
        'cookbook/async-basics',
        'cookbook/channels',
        'cookbook/generators',
        'cookbook/nursery',
        'cookbook/resilience',
        'cookbook/scheduler',
        'cookbook/collections',
        'cookbook/interior-mutability',
        'cookbook/shared-state',
        'cookbook/shared-ownership',
        'cookbook/refinements',
        'cookbook/shape-safe',
        'cookbook/calc-proofs',
        'cookbook/references',
        'cookbook/arenas',
        'cookbook/write-a-derive',
        'cookbook/cli-tool',
        'cookbook/tui',
        'cookbook/ffi',
        'cookbook/adding-verification',
        'cookbook/logic-functions',
        'cookbook/smt-debug',
        'cookbook/testing-recipes',
        'cookbook/linter-recipes',
      ],
    },
    {
      type: 'category',
      label: 'Migrating',
      link: {type: 'generated-index', slug: '/category/migrating'},
      items: [
        'migrating/from-rust',
        'migrating/from-typescript',
        'migrating/from-go',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'generated-index', slug: '/category/guides'},
      items: [
        'guides/faq',
        'guides/style-guide',
        'guides/best-practices',
        'guides/testing-best-practices',
        'guides/troubleshooting',
        'guides/performance',
        'guides/security',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      link: {type: 'generated-index', slug: '/category/community'},
      items: [
        'community/contributing',
        'community/code-of-conduct',
      ],
    },
    'roadmap',
    'changelog',
  ],
  language: [
    'language/overview',
    'language/syntax',
    'language/tagged-literals',
    {
      type: 'category',
      label: 'Type System',
      link: {type: 'generated-index', slug: '/category/language-types'},
      items: [
        'language/types',
        'language/refinement-types',
        'language/dependent-types',
        'language/linearity',
        'language/universes',
        'language/row-polymorphism',
        'language/tensor-types',
        'language/protocols',
        'language/generics',
        'language/type-properties',
        'language/capability-types',
      ],
    },
    'language/functions',
    {
      type: 'category',
      label: 'Patterns & Destructuring',
      link: {type: 'generated-index', slug: '/category/language-patterns'},
      items: [
        'language/patterns',
        'language/active-patterns',
        'language/destructuring',
        'language/comprehensions',
        'language/quantifiers',
        'language/copatterns',
      ],
    },
    {
      type: 'category',
      label: 'Memory & References',
      link: {type: 'generated-index', slug: '/category/language-memory'},
      items: [
        'language/memory-model',
        'language/references',
        'language/cbgr',
      ],
    },
    'language/modules',
    'language/context-system',
    'language/async-concurrency',
    'language/error-handling',
    {
      type: 'category',
      label: 'Metaprogramming',
      link: {type: 'doc', id: 'language/meta/overview'},
      items: [
        'language/meta/compilation-model',
        'language/meta/macro-kinds',
        'language/meta/quote-and-hygiene',
        'language/meta/staging',
        'language/meta/token-api',
        'language/meta/derives',
        'language/meta/literal-handlers',
        'language/meta/error-codes',
      ],
    },
    'language/proof-dsl',
    'language/attributes',
    'language/ffi',
  ],
  stdlib: [
    'stdlib/overview',
    {
      type: 'category',
      label: 'Core',
      link: {type: 'generated-index', slug: '/category/stdlib-core'},
      items: [
        'stdlib/base',
        'stdlib/collections',
        'stdlib/text',
        'stdlib/mem',
        'stdlib/intrinsics',
      ],
    },
    {
      type: 'category',
      label: 'I/O & System',
      link: {type: 'generated-index', slug: '/category/stdlib-io'},
      items: [
        'stdlib/io',
        'stdlib/time',
        'stdlib/sys',
        {
          type: 'category',
          label: 'TUI framework (term)',
          link: {type: 'doc', id: 'stdlib/term/overview'},
          items: [
            {
              type: 'category',
              label: 'Concepts',
              link: {type: 'generated-index', slug: '/category/term-concepts'},
              items: [
                'stdlib/term/concepts/architecture',
                'stdlib/term/concepts/elm-pattern',
                'stdlib/term/concepts/event-loop',
                'stdlib/term/concepts/rendering',
                'stdlib/term/concepts/layout-system',
              ],
            },
            'stdlib/term/widgets/overview',
            {
              type: 'category',
              label: 'Guides',
              link: {type: 'generated-index', slug: '/category/term-guides'},
              items: [
                'stdlib/term/guides/async-commands',
                'stdlib/term/guides/styling-theming',
                'stdlib/term/guides/layout-guide',
                'stdlib/term/guides/keyboard-mouse',
                'stdlib/term/guides/testing-tui',
              ],
            },
            {
              type: 'category',
              label: 'Examples',
              link: {type: 'generated-index', slug: '/category/term-examples'},
              items: [
                'stdlib/term/examples/counter',
                'stdlib/term/examples/todo-app',
                'stdlib/term/examples/dashboard',
              ],
            },
            {
              type: 'category',
              label: 'API reference',
              link: {type: 'generated-index', slug: '/category/term-reference'},
              items: [
                'stdlib/term/reference/api-widgets',
                'stdlib/term/reference/api-app',
                'stdlib/term/reference/api-layout',
                'stdlib/term/reference/api-style',
                'stdlib/term/reference/api-event',
                'stdlib/term/reference/api-raw',
              ],
            },
            'stdlib/term/comparisons',
            'stdlib/term',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Concurrency',
      link: {type: 'generated-index', slug: '/category/stdlib-concurrency'},
      items: [
        'stdlib/async',
        'stdlib/sync',
        'stdlib/runtime',
      ],
    },
    {
      type: 'category',
      label: 'Network',
      link: {type: 'generated-index', slug: '/category/stdlib-network'},
      items: [
        'stdlib/net',
        'stdlib/http2',
        'stdlib/quic-http3',
        {
          type: 'category',
          label: 'TLS 1.3',
          link: {type: 'doc', id: 'stdlib/net/tls/index'},
          items: [
            'stdlib/net/tls/handshake',
            'stdlib/net/tls/extensions',
            'stdlib/net/tls/keyschedule',
            'stdlib/net/tls/record-layer',
          ],
        },
        {
          type: 'category',
          label: 'QUIC',
          link: {type: 'doc', id: 'stdlib/net/quic/index'},
          items: [
            'stdlib/net/quic/frames',
            'stdlib/net/quic/packets',
            'stdlib/net/quic/crypto',
            'stdlib/net/quic/transport-params',
            'stdlib/net/quic/recovery',
          ],
        },
        {
          type: 'category',
          label: 'HTTP/3',
          link: {type: 'doc', id: 'stdlib/net/http3/index'},
          items: [
            'stdlib/net/http3/frames',
            'stdlib/net/http3/qpack',
            'stdlib/net/http3/priority',
            'stdlib/net/http3/server-push',
          ],
        },
        'stdlib/proxy',
        'stdlib/protobuf',
        'stdlib/compress',
        'stdlib/encoding',
        'stdlib/signal',
        'stdlib/mesh',
      ],
    },
    {
      type: 'category',
      label: 'Compute',
      link: {type: 'generated-index', slug: '/category/stdlib-compute'},
      items: [
        'stdlib/math',
        'stdlib/simd',
      ],
    },
    {
      type: 'category',
      label: 'Meta & Proof',
      link: {type: 'generated-index', slug: '/category/stdlib-meta'},
      items: [
        'stdlib/meta',
        'stdlib/proof',
        'stdlib/theory-interop',
      ],
    },
    {
      type: 'category',
      label: 'Context & Security',
      link: {type: 'generated-index', slug: '/category/stdlib-security'},
      items: [
        'stdlib/context',
        'stdlib/security',
        {
          type: 'category',
          label: 'security — full docs',
          link: {type: 'doc', id: 'stdlib/security/overview'},
          items: [
            'stdlib/security/overview',
            {
              type: 'category',
              label: 'Cryptographic primitives',
              link: {type: 'generated-index', slug: '/category/stdlib-security-crypto'},
              items: [
                'stdlib/security/hash',
                'stdlib/security/mac',
                'stdlib/security/kdf',
                'stdlib/security/cipher',
                'stdlib/security/aead',
                'stdlib/security/ecc',
                'stdlib/security/pq',
                'stdlib/security/util',
                'stdlib/security/auth-primitives',
              ],
            },
            {
              type: 'category',
              label: 'Identity, secrets, policy',
              link: {type: 'generated-index', slug: '/category/stdlib-security-policy'},
              items: [
                'stdlib/security/spiffe',
                'stdlib/security/secrets',
                'stdlib/security/labels',
                'stdlib/security/regions',
                'stdlib/security/capabilities',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Observability',
      link: {type: 'generated-index', slug: '/category/stdlib-observability'},
      items: [
        'stdlib/tracing',
        'stdlib/metrics',
      ],
    },
    {
      type: 'category',
      label: 'Data',
      link: {type: 'generated-index', slug: '/category/stdlib-data'},
      items: [
        'stdlib/database',
        'stdlib/database-sqlite-architecture',
        'stdlib/database-postgres',
        'stdlib/database-mysql',
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      link: {type: 'generated-index', slug: '/category/stdlib-foundations'},
      items: [
        'stdlib/eval',
        'stdlib/control',
        'stdlib/concurrency',
        'stdlib/logic',
        'stdlib/types',
      ],
    },
  ],
  architecture: [
    'architecture/overview',
    'architecture/compilation-pipeline',
    'architecture/vbc-bytecode',
    'architecture/runtime-tiers',
    'architecture/cbgr-internals',
    'architecture/codegen',
    'architecture/smt-integration',
    'architecture/verification-pipeline',
    'architecture/execution-environment',
    'architecture/incremental-compilation',
    'architecture/module-system',
    'architecture/crate-map',
    'architecture/lint-engine',
  ],
  reference: [
    'reference/grammar-ebnf',
    'reference/keywords',
    'reference/operators',
    'reference/builtins',
    'reference/meta-functions',
    'reference/tactics',
    'reference/attribute-registry',
    'reference/cli-commands',
    'reference/verum-toml',
    'reference/lint-configuration',
    'reference/lint-rules',
    'reference/glossary',
  ],
};

export default sidebars;
